//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `client.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package client;

/** @hidden */
public class _ReporterPrxI extends com.zeroc.Ice._ObjectPrxI implements ReporterPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
