//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `office.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package office;

public interface OfficeServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default int reportTaxReturn(ReportData data, int _return)
    {
        return reportTaxReturn(data, _return, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int reportTaxReturn(ReportData data, int _return, java.util.Map<String, String> context)
    {
        return _iceI_reportTaxReturnAsync(data, _return, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> reportTaxReturnAsync(ReportData data, int _return)
    {
        return _iceI_reportTaxReturnAsync(data, _return, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> reportTaxReturnAsync(ReportData data, int _return, java.util.Map<String, String> context)
    {
        return _iceI_reportTaxReturnAsync(data, _return, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_return -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_reportTaxReturnAsync(ReportData iceP_data, int iceP_return, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "reportTaxReturn", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ReportData.ice_write(ostr, iceP_data);
                     ostr.writeInt(iceP_return);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int reportIdCardRequest(ReportData data, int age)
    {
        return reportIdCardRequest(data, age, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int reportIdCardRequest(ReportData data, int age, java.util.Map<String, String> context)
    {
        return _iceI_reportIdCardRequestAsync(data, age, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> reportIdCardRequestAsync(ReportData data, int age)
    {
        return _iceI_reportIdCardRequestAsync(data, age, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> reportIdCardRequestAsync(ReportData data, int age, java.util.Map<String, String> context)
    {
        return _iceI_reportIdCardRequestAsync(data, age, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_age -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_reportIdCardRequestAsync(ReportData iceP_data, int iceP_age, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "reportIdCardRequest", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ReportData.ice_write(ostr, iceP_data);
                     ostr.writeInt(iceP_age);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int reportTradePermissionRequest(ReportData data, int businessId)
    {
        return reportTradePermissionRequest(data, businessId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int reportTradePermissionRequest(ReportData data, int businessId, java.util.Map<String, String> context)
    {
        return _iceI_reportTradePermissionRequestAsync(data, businessId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> reportTradePermissionRequestAsync(ReportData data, int businessId)
    {
        return _iceI_reportTradePermissionRequestAsync(data, businessId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> reportTradePermissionRequestAsync(ReportData data, int businessId, java.util.Map<String, String> context)
    {
        return _iceI_reportTradePermissionRequestAsync(data, businessId, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_businessId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_reportTradePermissionRequestAsync(ReportData iceP_data, int iceP_businessId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "reportTradePermissionRequest", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ReportData.ice_write(ostr, iceP_data);
                     ostr.writeInt(iceP_businessId);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default void connect(int reporterId, client.ReporterPrx reporter)
    {
        connect(reporterId, reporter, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void connect(int reporterId, client.ReporterPrx reporter, java.util.Map<String, String> context)
    {
        _iceI_connectAsync(reporterId, reporter, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> connectAsync(int reporterId, client.ReporterPrx reporter)
    {
        return _iceI_connectAsync(reporterId, reporter, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> connectAsync(int reporterId, client.ReporterPrx reporter, java.util.Map<String, String> context)
    {
        return _iceI_connectAsync(reporterId, reporter, context, false);
    }

    /**
     * @hidden
     * @param iceP_reporterId -
     * @param iceP_reporter -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_connectAsync(int iceP_reporterId, client.ReporterPrx iceP_reporter, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "connect", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_reporterId);
                     ostr.writeProxy(iceP_reporter);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), OfficeServicePrx.class, _OfficeServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), OfficeServicePrx.class, _OfficeServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), OfficeServicePrx.class, _OfficeServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static OfficeServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), OfficeServicePrx.class, _OfficeServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static OfficeServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, OfficeServicePrx.class, _OfficeServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static OfficeServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, OfficeServicePrx.class, _OfficeServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default OfficeServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (OfficeServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default OfficeServicePrx ice_adapterId(String newAdapterId)
    {
        return (OfficeServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default OfficeServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (OfficeServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default OfficeServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (OfficeServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default OfficeServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (OfficeServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default OfficeServicePrx ice_connectionCached(boolean newCache)
    {
        return (OfficeServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default OfficeServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (OfficeServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OfficeServicePrx ice_secure(boolean b)
    {
        return (OfficeServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default OfficeServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (OfficeServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default OfficeServicePrx ice_preferSecure(boolean b)
    {
        return (OfficeServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default OfficeServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (OfficeServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default OfficeServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (OfficeServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default OfficeServicePrx ice_collocationOptimized(boolean b)
    {
        return (OfficeServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default OfficeServicePrx ice_twoway()
    {
        return (OfficeServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default OfficeServicePrx ice_oneway()
    {
        return (OfficeServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default OfficeServicePrx ice_batchOneway()
    {
        return (OfficeServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default OfficeServicePrx ice_datagram()
    {
        return (OfficeServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default OfficeServicePrx ice_batchDatagram()
    {
        return (OfficeServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default OfficeServicePrx ice_compress(boolean co)
    {
        return (OfficeServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default OfficeServicePrx ice_timeout(int t)
    {
        return (OfficeServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default OfficeServicePrx ice_connectionId(String connectionId)
    {
        return (OfficeServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default OfficeServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (OfficeServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::office::OfficeService";
    }
}
